### ISSUE TITLE
请教下大佬，如何全局注册并使用 message组件

### ISSUE THREAD

**Issue by renhhhCSDN** [ibwei/vue3-ts-base#2]
vue2.0是通过 把message挂载到vue原型，vue3.0在setup中怎么使用message组件，按项目的配置，还是不能使用

1. config.js 引入 message组件并添加到 AppConfig对象上
2.在main.ts中配置app.config.globalProperties = AppConfig
3.跟目录下创建global.d.ts 
4.在组件中，setup中使用报错，不能在setup中使用this

**Comment by ibwei** [comment]
目前只支持在 optionsApi 中以 this.$message使用,如果需要在 setup 中使用,似乎只能手动引入 message
`import { message } from 'ant-design-vue';`
当然你有更好的方法,也可以告知我.

**Comment by renhhhCSDN** [comment]
好的，谢谢

**Comment by ibwei** [comment]
> 目前只支持在 optionsApi 中以 this.$message使用,如果需要在 setup 中使用,似乎只能手动引入 message
> `import { message } from 'ant-design-vue';`
> 当然你有更好的方法,也可以告知我.

还可以通过 vue 的 provide和 inject 功能实现，这是目前来说最佳的实践了。
