### ISSUE TITLE
how to dispatch actions

### ISSUE THREAD

**Issue by ZhengXingchi** [ibwei/vue3-ts-base#4]
in a.vue page
eg :how to dispatch actions
```
created(){
   this.$store.dispatch('refreshToken') //unknown action type: refreshToken
}
```

**Comment by ZhengXingchi** [comment]
answer by my  self:
`this.$store.dispatch('user/refreshToken')`

**Comment by ibwei** [comment]
> answer by my self:
> `this.$store.dispatch('user/refreshToken')`

you also can dispatch action by util function,like this
```javascript
dispatchActions<UserActionsType>('user','refreshToken')
```
