### ISSUE TITLE
首页加载太慢

### ISSUE THREAD

**Issue by longer008** [ibwei/vue3-ts-base#5]
![截图](https://b1.sbimg.org/file/chevereto-jia/2020/12/25/Qjaal.png)
https://b1.sbimg.org/file/chevereto-jia/2020/12/25/Qjaal.png

**Comment by longer008** [comment]
![截图](https://b1.sbimg.org/file/chevereto-jia/2020/12/25/Qjaal.png)

**Comment by ibwei** [comment]
图片挂了，看不到你的描述。
如果是我的 github page 的网页，的确是慢,是环境问题，跟代码本身关系不大。

另外，目前build 出来之后的一共只有 2M，还包括一些按需加载的文件，wbpack在 build 时也没有提示有需要优化的大文件，如果太慢，你可以检查一下客观环境因素。

**Comment by ibwei** [comment]
> ![截图](https://camo.githubusercontent.com/0ecb8a0432c66629fa7dcdb1d2d21d0d9232333ae63a401c7a5d1bd62fd69265/68747470733a2f2f62312e7362696d672e6f72672f66696c652f63686576657265746f2d6a69612f323032302f31322f32352f516a61616c2e706e67)
> https://b1.sbimg.org/file/chevereto-jia/2020/12/25/Qjaal.png

已做代码分离。
