### ISSUE TITLE
请问兼容性有测试过吗？

### ISSUE THREAD

**Issue by ohion** [ibwei/vue3-ts-base#9]
请问这个项目的兼容性如何，目前发现谷歌可以打开，火狐页面打不开。

**Comment by ibwei** [comment]
![image](https://user-images.githubusercontent.com/25237993/111113369-9ff5a380-859c-11eb-9328-35e73e8f2f60.png)
操作系统: mac 10.15.7，浏览器：firefox 74.0 (64 位) 能如期打开页面。如果你排除了网络异常的情况外，打开控制台有报错信息吗？如果发现错误，请与我联系。

关于兼容性说明：基于此代码基础架子搭建的中型项目已在生产环境稳定运行，抛开 IE 浏览器不谈，暂时没有发现 vue3 本身所带来的兼容性问题，这么久以来，只发现了一个 ant-design-vue 的下拉选择框在 360 极速浏览器中打开会自动关闭的 bug，希望这个信息对你有所参考。
